fiatconnect/fiatconnect-types

CHANGELOG.md, package.json, src/index.ts
Adds support for the PersonalDataAndDocuments KYC schema, required by PayChant. See [here](https://github.com/fiatconnect/specification/blob/main/fiatconnect-api.md#728-personaldataanddocuments) for the related spec.
=> feat(kyc): Add support for PersonalDataAndDocuments KYC schema

CHANGELOG.md, package.json
See #6. I've unpublished v1.0.2 from NPM. Once this is merged, I'll republish under v2.0.0, which is semantically correct, since we've removed a mock KYC type, so this update should be categorized as breaking.
=> chore(release): Fix build issue

src/index.ts
Without the `Partial` every `FiatAccountType` is required as a key
=> fix(fiat-account): record should be partial

src/index.ts
BREAKING CHANGE: quoteId added as required parameter for transfer requests
Other:
- quoteId added to quote response
- guaranteedUntil made required in quote response
=> refactor!: quote ids

README.md, package.json
Running yarn release on a branch generates the tag on a commit on the branch, which is different from the commit on `main`. This updates the command to not generate the tag and adds doc on creating the tag manually
=> chore: update release command, instructions

src/index.ts
This will be used in both api-starter and the fiatconnect-sdk.
Also moved auth request body to be along with other endpoint types
=> feat(network): add enum for network

src/index.ts
BREAKING CHANGE: 
- Removed query params for POST /accounts and added body. Also renamed `Add` to `Post`.
- Export map of fiat account schemas instead of individual schemas
For https://github.com/fiatconnect/specification/commit/df6ff3dbc7d1422bbcef85515d58bc357963711d
=> feat(accounts): update params for fiat accounts endpoint

src/index.ts
BREAKING CHANGE: no longer export individual schemas explicitly
Identical change to fiat account schemas in #33
=> feat(kyc): expose map type of kyc schemas

src/index.ts
The KYC status enum currently does not have the `'Kyc'` prefix in front of each status, which differs from the [expectation in the spec](https://github.com/fiatconnect/specification/blob/main/fiatconnect-api.md#811-kycstatusenum).
=> fix(KYC): Prefix KYC statuses

src/index.ts
The current types allow any event type value for a specific body. E.g., `WebhookKycStatusRequestBody` could have `TransferOutStatusEvent` as event type. This ensures payload matches the event type.
=> fix(webhook): ensure event type and payload matches

src/index.ts
timestamp field was missing from the webhook request
=> fix(webhook): add timestamp

package.json, yarn.lock
`yarn lint` now works. kind of annoying that jest needs to be added as a dev dep for this (given that there are no tests currently defined), but at least it's just a dev dep...
the alternative would be dropping the valora linter deps, which seems less ideal
=> fix(lint): add missing deps for linting

.github/workflows/workflow.yaml, package.json
linting was broken for who knows how long. This should prevent that from happening silently again, and give us a baseline for CD and other kinds of checks we may want
=> ci: add yaml and checks

.github/workflows/workflow.yaml
semantic-release docs left it somewhat unclear whether we'd need this, but I think we do because of how GH actions works now (as opposed to when the semantic-release docs were written) and maybe (also?) due to our branch protection rules
(the current workflow fails on the NPM publish step, see [here](https://github.com/fiatconnect/fiatconnect-types/runs/8116340437?check_suite_focus=true))
=> chore(cd): switched to using personal access token for CD

.github/workflows/workflow.yaml, package.json
turns out `yarn publish` tries to publish to the NPM registry, even if it's over-ridden in `package.json`. This isn't what I actually wanted-- was just trying to run `npx semantic-release`
=> chore(cd): avoiding 'yarn publish' (has special meaning with yarn)

src/index.ts
to match spec [here](https://github.com/fiatconnect/specification/blob/main/fiatconnect-api.md#913-webhookeventtypeenum)
=> fix(webhooks): add Webhook prefix to webhook event types

src/index.ts
See [here](https://github.com/fiatconnect/specification/blob/main/fiatconnect-api.md#341111-request-body). Address is actually a required field when fetching quotes, but we currently do not require nor even allow it as a parameter.
BREAKING CHANGE: New parameter required on quotes
=> feat(quotes)!: Make address a required field when fetching quotes

.github/workflows/workflow.yaml
more secure, works just as well for publishing tags and releases, and PAT doesn't actually get us anything extra due to branch protection rules
=> chore(cd): use GITHUB_TOKEN instead of personal access token

src/webhook.ts
WebhookRequestBody used to be a generic type and a lot of existing code was using these individual schemas through the generic reference, so we should expose them individually now 
This should have been included with the original zod schema creation, but was overlooked
=> feat(webhook): expose individual webhook request body schemas

src/quote.ts
to catch the issue we saw today with bitssa's allowedValues field on mobile money operators
=> chore(validation): require nonempty lists for allowedValues

src/fiat-account.ts
Currently, the Mobile Money account schema requires the operator to be a member of an enum of supported operators. The FiatConnect spec has [been changed](https://github.com/fiatconnect/specification/pull/88) to remove this and instead only require the operator to be a string. 
This PR updates the types repo to match the updated spec and is a part of [ACT-581](https://linear.app/valora/issue/ACT-581/update-fc-deps-to-account-for-mobile-money-spec-change).
=> fix(fiatAccount)!: remove supported operator enum

src/common.ts, src/transfer.ts
- Added InvalidQuote as possibleError in FiatConnectErrors as required by the specification (https://github.com/fiatconnect/specification/blob/main/fiatconnect-api.md#3441323-invalidquote)
- Added TransferReceivedFiatFunds as possible TransferStatus as required by the specification (https://github.com/fiatconnect/specification/blob/main/fiatconnect-api.md#41-transfers-in)
=> fix(enums): add missing error type and transfer status

src/common.ts, src/fiat-account.ts, src/kyc.ts
similar to https://github.com/fiatconnect/fiatconnect-types/pull/121 but includes more semantics in the zod schemas, in particular:
- when the back of the document is required
- what the email should look like
also more DRY with the existing kyc schema
=> feat: add PersonalDataAndDocumentsDetailed kyc schema

src/transfer.ts, src/webhook.ts
Per [this change](https://github.com/fiatconnect/specification/pull/95) to the specification, adds `txHash` as an optional field to transfer (in) statuses.
Since this PR encodes a good deal of semantics onto the transfer status endpoints/webhooks, this PR introduces a breaking change.
=> fix(transfers)!: Add txHash to transfer in statuses
